### ISSUE TITLE
Use with custom `standalone.js`

### ISSUE THREAD

**Issue by czosel** [loilo/prettier-php-playground#151]
Hi @loilo,

You mentioned over at https://github.com/prettier/plugin-php/pull/1286#pullrequestreview-339733209 that it's possible to use the playground with a custom `standalone.js` file - can you share some details how to do this? :slightly_smiling_face: 

Thanks!

**Comment by czosel** [comment]
Nevermind, I just realized you built this straight into the UI! I missed the new icon in the screenshot you posted :man_facepalming:

**Comment by loilo** [comment]
To be honest, I considered framing the new icon with a red border in the screenshot because it really is pretty subtle. 😅
